# Changes here will be overwritten by Copier
_commit: f812aaa
_src_path: https://github.com/python-project-templates/base.git
add_docs: false
add_extension: python
add_wiki: false
email: t.paine154@gmail.com
github: 1kbgz
project_description: Union handling for fsspec filesystems
project_name: fsspec-union
python_version_primary: '3.11'
team: the fsspec-union authors
